services:
  minecraftegory-front:
    build: .
    container_name: minecraftegory-front
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - minecraftegory-front-node-modules:/app/nodes_modules

volumes:
  minecraftegory-front-node-modules:
